config-service:
  image: chrkwbr/config-service
  environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DOCKER_IP=$DOCKER_IP
  ports:
    - 8888:8888
discovery-service:
  image: chrkwbr/discovery-service
  ports:
    - 8761:8761
  environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DOCKER_IP=$DOCKER_IP
edge-service:
  image: chrkwbr/edge-service
  ports:
    - 9999:9999
  links:
    - user-service
    - discovery-service
    - config-service
  environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DOCKER_IP=$DOCKER_IP