server:
  port: 8080
logging:
  exception-conversion-word: "\t%replace(%replace(%xEx){'\n','@n@'}){'\t','    '}%nopex"
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${logging.pattern.level:%5p}) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %replace(%m){'\n','@n@'}${logging.exception-conversion-word:%wEx}%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${logging.pattern.level:%5p} ${PID: } --- [%15.15t] %-40.40logger{39} : %replace(%m){'\n','@n@'}${logging.exception-conversion-word:%wEx}%n"
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,prometheus,gateway
  metrics:
    export:
      prometheus:
        rsocket:
          host: localhost
    tags:
      application: ${spring.application.name}
      instance_id: ${management.metrics.tags.application}:0
      organization: example.com
      space: develop
spring:
  cloud:
    consul:
      discovery:
        #        instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}
        instance-id: ${spring.application.name}:${random.int[1,999999]}
#        host: localhost
#        port: 8500
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ui_path_route
          uri: ${ui.url:http://127.0.0.1:8000}
          predicates:
            - Path=/**
          filters:
            - name: AccessLogging
            - RewritePath=/(?<path>.*), /$\{path}
        - id: web_path_route
          uri: ${web.url:http://localhost:9000}
          predicates:
            - Path=/api/**
          filters:
            - name: AccessLogging
            - RewritePath=/api/(?<path>.*), /$\{path}
      loadbalancer:
        use404: true
      metrics:
        enabled: true
  profiles:
    active: development
  # TODO
  sleuth:
    sampler:
      rate: 30
    web:
      additional-skip-pattern: /actuator.*
# TODO
security:
  oauth2:
    resource:
      user-info-uri: http://localhost/uaa/user #TODO
  ignored: /catalog/**
# TODO
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/ #TODO
